name: Preproc data and train model

on: 
  workflow_dispatch
 
jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: "3.11"
      - name: Install dependencies
        run: make requirements
      - name: Create kaggle directory
        env: 
          KAGGLE_KEY: ${{ secrets.KAGGLE_API_KEY }}
        run: |
          mkdir -p $HOME/.config
          mkdir -p $HOME/.config/kaggle
          echo "$KAGGLE_KEY" > $HOME/.config/kaggle/kaggle.json
          chmod 600 $HOME/.config/kaggle/kaggle.json
      - name: Run preprocessing
        run: make preprocess
      - name: Upload preprocessed data
        uses: actions/upload-artifact@v4
        with:
          name: processed-data
          path: data/processed
  train:
    runs-on: ubuntu-latest
    needs: preprocess
    permissions:
      contents: write  # This gives the token write access to the repository contents
      actions: write   # ✅ Allows triggering other workflows!
    steps: 
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download processed data
        uses: actions/download-artifact@v4
        with:
          name: processed-data
          path: data/processed
      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: "3.11"
      - name: Install dependencies
        run: make requirements
      - name: Setup MlFlow
        run: |
          mlflow ui --backend-store-uri postgresql://${{secrets.MLFLOWDBUSERNAME}}:${{secrets.MLFLOWDBPASS}}@${{secrets.MLFLOWDBENDPOINT}}:${{secrets.MLFLOWDBPORT}}/${{secrets.MLFLOWDB}} --default-artifact-root s3://${{secrets.ARTIFACT_BUCKET}}/models --host 0.0.0.0 --port 5000  
      - name: Run training
        env:
          MLFLOW_TRACKING_URI: postgresql://${{secrets.MLFLOWDBUSERNAME}}:${{secrets.MLFLOWDBPASS}}@${{secrets.MLFLOWDBENDPOINT}}:${{secrets.MLFLOWDBPORT}}/${{secrets.MLFLOWDB}}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: make train

      - name: Upload trained model
        uses: actions/upload-artifact@v4
        with:
          name: trained-model
          path: models/

      - name: Trigger Predict Workflow
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/predict_on_model_change.yml/dispatches \
          -d '{"ref":"main"}'
